[package]
name = "typst-ide"
description = "IDE functionality for Typst."
version = { workspace = true }
rust-version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
categories = { workspace = true }
keywords = { workspace = true }
readme = { workspace = true }

[dependencies]
typst = { workspace = true }
typst-eval = { workspace = true }
comemo = { workspace = true }
ecow = { workspace = true }
<<<<<<< HEAD
if_chain = { workspace = true }
pathdiff = { workspace = true }
=======
pathdiff = { workspace = true }
rustc-hash = { workspace = true }
>>>>>>> dd1e6e94f73db6a257a5ac34a6320e00410a2534
serde = { workspace = true }
unscanny = { workspace = true }

[dev-dependencies]
typst-assets = { workspace = true, features = ["fonts"] }
typst-dev-assets = { workspace = true }
once_cell = { workspace = true }

[lints]
workspace = true
